
language: scala

matrix:
  include:
  - jdk: oraclejdk9
    scala: 2.12.4
  - jdk: oraclejdk8
    scala: 2.12.4
  - jdk: oraclejdk8
    scala: 2.11.11

script:
 - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx1024M test

