
language: scala

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 12.1.0
  - nvm use 12.1.0
  - npm install
  - npm install jsdom

# Unfortunately, a JDK 8 is missing here (this project must work on JDK 8)

matrix:
  include:
  - jdk: oraclejdk9
    scala: 3.0.1
  - jdk: openjdk13
    scala: 3.0.1
  - jdk: openjdk13
    scala: 2.13.6

script:
 - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx2G test

