
language: scala

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom

matrix:
  include:
  - jdk: oraclejdk9
    scala: 2.12.10
  - jdk: openjdk11
    scala: 2.13.1
  - jdk: oraclejdk9
    scala: 2.13.1

script:
 - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx1024M test

